### ISSUE TITLE
Status of spacemacs layer

### ISSUE THREAD

**Issue by favetelinguis** [davidlandry93/ros-helm#4]
Hi what is the status of this project? If it is still active how can I get it working, I have been trying to add helm-ros as a layer but it is not avaliable?

**Comment by davidlandry93** [comment]
helm-ros a project I did real quick, as a way to teach myself Emacs Lisp. It should not be considered as active. The companion Spacemacs layer can be found at [](https://github.com/davidlandry93/spaceros). It hasn't been used by me in a while!
